### PR TITLE
Serialization queue

### PR DESCRIPTION
**Pull request by flippinjoe21**
This should not be merged until after [PR #3](https://github.com/urbn/URBNRouter/pull/3)

### CODE REVIEW

**Comment by jgrandelli** [comment]
Did you combine the emtpy and the queue stuff?

**Comment by jgrandelli** [comment]
yes

**Comment by jgrandelli** [comment]
@Dutcher & @ndis1

**Comment by flippinjoe21** [comment]
I based this PR off of the empty stuff to avoid conflicts

**Comment by jgrandelli** [comment]
@flippinjoe21 please redo this to get rid of the merged commits. Sometimes github sucks at this

**Pull request closed without merging**
